---
title: "Lab: The 12 Days of Christmas"
author: "Austin Lautenbach, Sean Leader, Gabriel Barney, Rachael Koenigsberg"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    css: styles.css
---

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 10px;}
</style>
<div class = "blue">

Nice work! You have no revisions! 
  
**Score** (out of 7 questions):  

</div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages for Functions
library(dplyr)
library(glue)
library(stringr)
library(purrr)
library(english)
```

```{r, include=FALSE}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")
```

---

## Step One:  Plurals

```{r}
pluralize_gift <- function(gift){

# switch case
gift <- case_when(
  str_detect(gift, "y$") ~ str_replace(gift, "y$", "ies"),
  str_detect(gift, "oo") ~ str_replace(gift, "oo", "ee"),
  TRUE ~ str_c(gift, "s")
)
  
return(gift)
}

```

### Test Your Function

```{r}

pluralize_gift(xmas$Gift.Item)

purrr::map_chr(xmas$Gift.Item, pluralize_gift)

```

---

## Step Two: Creating sentences

```{r}
make_phrase <- function(num, num_word, item, verb, adjective, location) {
  
  ## Step 1: Replace NAs with blank strings
  verb <- str_replace_na(verb, "")
  adjective <- str_replace_na(adjective, "")
  location <- str_replace_na(location, "")
  
  ## Step 2: Pluralize the gift if needed
  ## Items with numbers larger than 1 should be pluralized
  ## Single items starting with a vowel should have "an" in front
  ## All other single items should have "a" in front
  
  vowel_start <- str_sub(item, 1, 1) %>% str_detect("[aeiouAEIOU]")
  
  if (num > 1) {
    
    item <- pluralize_gift(item)
    
  } else if (vowel_start) {
    
    num_word <- 'an'  
    
  } else {
    
    num_word <- 'a'
    
  }
  
  glue::glue("{num_word} {adjective} {item} {verb} {location}") %>%
    str_squish()
  
}
```

# Test Your Function

```{r}
xmas <- xmas %>%
  mutate(
    Full.Phrase = pmap_chr(list(Day, as.character(english(Day)), Gift.Item, Verb, Adjective, Location), 
                           make_phrase)
  )

```

---

## Step Three:  Iteration.

```{r}
sing_line <- function(dataset, line, phrase_col){

  # Step 1: Setup the intro line

  num_word <- ordinal(line)

  intro <- glue::glue("On the {num_word} day of Christmas, my true love gave to me,")

  # Step 2: Sing the gift phrases

    phrases <- dataset %>% 
      pull({{phrase_col}})

    if (line == 1) {
      return(glue("{intro} \n {phrases[1]}"))
    }
    
    phrases[1] <- glue("and {phrases[1]}")
    phrases <- rev(phrases[1:line])
    phrases <- paste(phrases, collapse = '\n')
      
    return(glue("{intro} \n {phrases}"))
    
}

```

Source (rev): <https://stat.ethz.ch/R-manual/R-patched/library/base/html/rev.html>

Source (paste): <https://www.journaldev.com/40396/paste-in-r#:~:text=Output%20%3D%20%E2%80%9C1%26two%263%26four%265%26six%E2%80%9D-,The%20paste()%20function%20with%20collapse%20argument,the%20elements%20in%20the%20vector.>

Test:

```{r}
sing_line(xmas, 
          line = 5, 
          phrase_col = Full.Phrase)
```

---

## Step Four: Use Your Functions!


```{r}
xmas2 <- xmas %>%
  mutate(
    day.num = as.character(english::english(Day)), 
    Full.Phrase = pmap_chr(list(num = Day, 
                                num_word = day.num, 
                                item = Gift.Item, 
                                verb = Verb, 
                                adjective = Adjective, 
                                location = Location), 
                           make_phrase)
  )

map_chr(1:12, ~sing_line(xmas2, .x, Full.Phrase)) %>%
  str_c(collapse = "\n") %>%
  cat()

```
